# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Monica' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Monica
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'

  target 'MonicaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
